### ISSUE TITLE
Refactor Editor state to a new class

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#125]
We currently keep a bunch of flags/fields and methods, that indicate the current state of the Editor, directly in the EditorTopComponent. To avoid this growing too large and also for the better readability, we should refactor this to a new class, called "EditorState" and keep those fields and methods there. 
Those fields include:
```
    private boolean dirty = false;
    private boolean modified = false;
    private boolean previewDisplayed = true;
    private File currentFile;
    private DbxState dbxState;
```
and all should be moved to a new class. The EditorTopComponent should expose a single method, that returns an instance of EditorState class.

**Comment by brendajean1123** [comment]
Hi, I would like to take a stab at this issue.  I am new to recent development.  I forked this repository to mine and added a file, EditorState.java, and made some changes to EditorTopComponent.java to create an instance to use instead of the local variables.  Have yet to learn how to do a "Pull Request."

**Comment by brendajean1123** [comment]
Not sure how this system works, so here is my github: 
https://github.com/brendajean1123/Open-LaTeX-Studio.
