### ISSUE TITLE
Error connecting to dropbox

### ISSUE THREAD

**Issue by Suleman-Elahi** [sebbrudzinski/Open-LaTeX-Studio#151]
![image](https://user-images.githubusercontent.com/24384996/35844916-dcb82886-0b35-11e8-90e6-b00ba7ff6c41.png)
 
After entering correct access token, then application failed to connect.

**Comment by sebbrudzinski** [comment]
Thanks for reporting @Suleman-Elahi , I'll try to get to this sometime soon. My guess is that this is due to Dropbox disabling support for their v1 API. This also means that Open LaTeX Studio will need a new release, and only that new release will have the Dropbox support working correctly.

**Comment by glandre** [comment]
Hey @sebbrudzinski, how's everything? It's been a while, I know...

Your guess was correct. I did some debug here, and the problem was a `Bad Request (400)` response from the deprecated method `getAccountInfo`.

There are lots of places to change, but in general, the changes are simple. let me know if you already have some work in progress... Otherwise, I can work on it.

Actually, I started to work on it. You can check the progress here: https://github.com/sebbrudzinski/Open-LaTeX-Studio/compare/master...glandre:glandre/dropbox-upgrade

FYI:
- I'm following this migration guide: https://www.dropbox.com/developers/reference/migration-guide#metadata-mapping
- This is a working example that is useful as a starting point: https://github.com/dropbox/dropbox-sdk-java/blob/master/examples/tutorial/src/main/java/com/dropbox/core/examples/tutorial/Main.java
- Here is the API reference for the last version of the SDK: https://dropbox.github.io/dropbox-sdk-java/api-docs/v3.0.x/
- And this is the reference to the old one (useful for comprehending the current state of the code): http://dropbox.github.io/dropbox-sdk-java/api-docs/v1.8.x

**Comment by sebbrudzinski** [comment]
Hey @glandre  - great to hear from you. I've also started working on it and was also planning to upgrade straight to v3. I'm happy to let you continue, but if you get stuck on something, let me know and I'll take a look. I'm also happy to test once all is done.

**Comment by glandre** [comment]
@sebbrudzinski, I'm glad to be back! 
I'll try to send a PR to you by this weekend.
Cheers!

**Comment by sebbrudzinski** [comment]
Fixed by @glandre - closing
