### ISSUE TITLE
Auto-sync files to Dropbox

### ISSUE THREAD

**Issue by sebbrudzinski** [sebbrudzinski/Open-LaTeX-Studio#21]
Currently to save files to Dropbox, user has got to manually trigger the action, by selecting "Save progress" action in menu. We could add an ability to enable auto-sync file every specified amount of time.

**Comment by WhiteHsu** [comment]
Have anybody worked on this? If not, may I give it a try?

**Comment by sebbrudzinski** [comment]
@WhiteHsu It's yours! Good luck :)

**Comment by WhiteHsu** [comment]
@sebbrudzinski 

After some study, I have question to this feature and would like to ask your suggestion.

For current version, the update will sync to Dropbox unless clicking the "Save Progress" option. After clicking it, update will not only sync to Dropbox but there'll be new record created on the "Dropbox Revisions" list on the table below.
![pic01](https://cloud.githubusercontent.com/assets/7831418/17323152/94c0221a-58d3-11e6-9dae-4f6d5e1bac30.png)

So I'm wandering if we have auto-sync feature, after an auto save, do we need to create new record in "Dropbox Revisions" as well? 
- If it'll create new record, because auto-sync may be triggered every few minutes, then we may have a lot of revision records in "Dropbox Revisions", which seems very poor user experience.
- If it'll NOT create new record, and the auto-sync will overwrite the latest record in "Dropbox Revisions". However, if user would like to restore back to an old version, he/she may find the old version has already been overwritten by auto-sync, so the old version may not exist any more. This seems not a good way to implement this feature either.
- Maybe we can have an auto sync will NOT update anything in "Dropbox Revisions", there'll be new record unless manually selecting "Save Progress"? I'm not sure if this's a good way and afraid whether this will make other issue, such as to make any data or update missed?

I'm not sure if I'm thinking on the right way and need your help to suggest. Please kindly help provide your feedback or comments. Thank you very much.

**Comment by WhiteHsu** [comment]
@sebbrudzinski 

After some study, I have question to this feature and would like to ask your suggestion.

For current version, the update will sync to Dropbox unless clicking the "Save Progress" option. After clicking it, update will not only sync to Dropbox but there'll be new record created on the "Dropbox Revisions" list on the table below.
![pic01](https://cloud.githubusercontent.com/assets/7831418/17323152/94c0221a-58d3-11e6-9dae-4f6d5e1bac30.png)

So I'm wandering if we have auto-sync feature, after an auto save, do we need to create new record in "Dropbox Revisions" as well? 
- If it'll create new record, because auto-sync may be triggered every few minutes, then we may have a lot of revision records in "Dropbox Revisions", which seems very poor user experience.
- If it'll NOT create new record, and the auto-sync will overwrite the latest record in "Dropbox Revisions". However, if user would like to restore back to an old version, he/she may find the old version has already been overwritten by auto-sync, so the old version may not exist any more. This seems not a good way to implement this feature either.
- Maybe we can have an auto sync will NOT update anything in "Dropbox Revisions", there'll be new record unless manually selecting "Save Progress"? I'm not sure if this's a good way and afraid whether this will make other issue, such as to make any data or update missed?

So which is the recommended way to implement this feature? I'm not sure if I'm thinking on the right way and need your help to suggest. Please kindly help provide your feedback or comments. Thank you very much.

**Comment by sebbrudzinski** [comment]
@WhiteHsu We do not really have any choice here. The "Dropbox Revisions" list is managed by Dropbox itself. Every time a save to the file occurs, Dropbox automatically creates a revision entry I haven't done much research concerning this, but I believe there's no way to turn this off - feel free to verify. 

Having said that, I guess we are fine with having a lot of revision records for now. Perhaps the display of the revision records can be adjusted or grouped somehow later on, in a separate ticket, so the auto-save revisions appear together. For now, I'm fine with just having a list of all the revisions.

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
OK, I got it. Thanks for your reply. I'll update codes on this way.  :-)

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
I've raised pull request but it got failed on Travis CI:
https://travis-ci.org/sebbrudzinski/Open-LaTeX-Studio/jobs/157129183

Because I'm not familiar with Travis CI, may you help guide me how to view the root cause of CI failure? Thank you very much.

**Comment by sebbrudzinski** [comment]
@WhiteHsu Scroll to the bottom of the output and you will see a list of the checks that failed, right above the build summary.

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
Thanks for reply. I find it and already fix now. Please help review my code updates. Many thanks.  :-)

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
I have committed and pull request for this item but not gotten further response. May you kindly help check my updates and provide your valuable feedback? Please kindly let me know if there's anything wrong and where I should refine and improve (my Email is hsnu97526@gmail.com). Thank you very much.  :-)

Here's the URL of Pull Request:
https://github.com/sebbrudzinski/Open-LaTeX-Studio/pull/143

**Comment by sebbrudzinski** [comment]
The basic auto-sync has been implemented by @WhiteHsu so I'm closing this ticket. Improvements/enhancements to the existing auto-sync should have new tickets opened.

**Comment by WhiteHsu** [comment]
@sebbrudzinski 
Thanks for your help.  I'll pick another ticket to work.  :-)
