### ISSUE TITLE
Save action overwriting a file without confirmation

### ISSUE THREAD

**Issue by glandre** [sebbrudzinski/Open-LaTeX-Studio#83]
Repro steps:
- Open application
- Click Save Button (File->Save and Ctrl+S produces the same as well)
- At the Save Window (FileChooser), choose an existing file
- The file is saved overwritig the previous existing file

Ideally, in my opinion, it should work like **Save As** action, which asks for confirmation.

**Comment by WhiteHsu** [comment]
Hello,
I'm the new comer of this project. My name is White Hsu. I have development experience and have already built source codes. So may I take this issue as my 1st task to get started with Open-LaTeX? Please kindly help suggest. Thank you very much.  :-)

**Comment by sebbrudzinski** [comment]
Hello @WhiteHsu 
Yes, this is a great task to get you started with Open LaTeX Studio. In general, all issues marked with "Community friendly" label are identified by us as good starter tasks. Feel free to work on this :)

**Comment by WhiteHsu** [comment]
Hello @sebbrudzinski 
Thanks for your kind reply. I'll start to work on this on these days. Thank you very much.  :-)

**Comment by WhiteHsu** [comment]
Hello @sebbrudzinski 

After studying codes, I think we should insert codes into the class file latexstudio.editor.menu.SaveFile.java with similar codes to the SaveAs.java in the same package as below:
![pic01](https://cloud.githubusercontent.com/assets/7831418/14059301/efcd0b8a-f377-11e5-88c5-b69b9918cfdd.png)

However, before fixing this bug, may I ask a stupid question firstly? In my past experience, if we would like to have the SaveFile class extended ActionListener, in order to trigger its method actionPerformed(ActionEvent e), we need to have "addActionListener" in some where to add the SaveFile class into an object, which should be the "Save" button in this case. However, after searching, I cannot find any object to have "addActionListener" to add the "SaveFile" class. The following is my search result screen:
![pic02](https://cloud.githubusercontent.com/assets/7831418/14059328/7a56ab1c-f378-11e5-8830-0180de27e8e5.png)

None of search results above have "addActionListener" to add the "SaveFile" class. So I have a question that: If we don't use "addActionListener" to add the "SaveFile" class, how can we bind the Save button to the "SaveFile" class which is extended the ActionListener interface? Please kindly help reply my question and tell me how you do that. It'll be also helpful if you can tell me where are the codes to bind the Save button to the SaveFile.java class. Thank you very much.

**Comment by glandre** [comment]
Hi @WhiteHsu , I'm not entirely sure about the location of the "addActionListener" method. However, I suppose that it is taken care of by the Netbeans Framework.

Related to how to bind the Save button to "SaveFile", it's done by the SaveFile class annotations 
```
@ActionID(
        category = "File",
        id = "latexstudio.editor.SaveFile"
)
@ActionRegistration(
        iconBase = "latexstudio/editor/resources/icons/save.png",
        displayName = "#CTL_SaveFile"
)
@ActionReferences({
    @ActionReference(path = "Menu/File", position = 1300),
    @ActionReference(path = "Toolbars/File", position = 2222),
    @ActionReference(path = "Shortcuts", name = "D-S")
})
@Messages("CTL_SaveFile=Save")
```

Notice that the annotation `@Messages` is from NetbeansFramework (
`import org.openide.util.NbBundle.Messages;`

https://platform.netbeans.org/tutorials/nbm-paintapp.html

**Comment by sebbrudzinski** [comment]
@WhiteHsu @glandre 
Geraldo has provided the answers to most of your questions. Take a look at his comment and feel free to let us know if anything is still not quite clear. We do not have to explicitly add action listeners, because the NetBeans Platform framework does it for us, just like a lot of other UI stuff. The actions are controlled via the annotations on the classes implementing ActionListener interface. Those classes can be automatically generated by NetBeans, by right clicking on the module and selecting "Add action".

The key question here is how we want to handle duplicating logic between "Save as" and "Save" actions. I'd propose the simplest solution - moving the common logic to a separate class and invoking the same methods (with possibly different parameters) from both of those actions. If you have your own ideas, we may discuss them as well.

**Comment by WhiteHsu** [comment]
@glandre  @sebbrudzinski 
Oh, I got it!! Thanks for your clear explanation!! This's my first time to use NetBeans, I've mostly adopted Eclipse before. It seems I should get more familiar with NetBeans especially for the Action Control Framework.

So I'm planning my next steps as below:
1. To study the Action Control Framework in NetBeans, this should be very important for further development tasks.
2. Then next, I'm planning to create another separate class to have the common logic to check file existence under the package "latexstudio.editor.menu".

These're just drafted ideas. Please kindly provide your feedback and suggestions. Thank you very much.

**Comment by WhiteHsu** [comment]
@sebbrudzinski @glandre 
I've committed my code change and created a pull request:
https://github.com/sebbrudzinski/Open-LaTeX-Studio/pull/97

Because this's my first time to create pull request, please kindly help review and provide your valuable feedback. Any advice will be very appreciated. Thank you very much.

**Comment by sebbrudzinski** [comment]
Closing this ticket as the issue has been fixed by @WhiteHsu. Thanks!
